### ISSUE TITLE
"Breakable" glass in hazard course shooting range very difficult to break

### ISSUE THREAD

**Issue by milesrotaru** [DrBeef/Lambda1VR#13]
It didn't want to break until after I had tried holding the gun in both hands and then letting go. The target behind the now-broken glass also would not register being hit until I held the gun in both hands and then let go again. Both objects received bullet holes the whole time so it's not like I was missing.

**Comment by baggyg** [comment]
My guess at this point is you are seeing a genuine bug but attributing it to the wrong cause. 

The two handed just adjusts position, so unlikely that this would be affecting object properties in the world. 

Far more likely is exactly the same as https://github.com/DrBeef/Lambda1VR/issues/4. Investigation is ongoing on that but looks like bullet holes aren't quite matched up with the actual client ray tracing.

**Comment by baggyg** [comment]
I believe this is fixed along with my aforementioned issue #4
