### ISSUE TITLE
 Sometimes moving with the thumbstick is wrong/reversed

### ISSUE THREAD

**Issue by hfbassani** [DrBeef/Lambda1VR#15]
I don't know how to reproduce it, but it happened a few times while playing the first stage. It is as if the character's front was not aligned with my front/head. Holding the oculus button to reset position seems to change the direction but doesn't always solve the problem.

Great work, by the way!

**Comment by baggyg** [comment]
The direction follows the forward position of the off-hand controller, not your head. Just checking that this is not the reason for the confusion?

**Comment by hfbassani** [comment]
That's a good point. I'm pretty sure the controller was pointing forward, but I'll check that again.

**Comment by TheInimitable** [comment]
Sounds similar to something I was confused about.  In the current control scheme, if you're using the left-handed cvar, the left controller controls the locomotion but the off-hand (right) controller still controls your orientation.

**Comment by hfbassani** [comment]
Yes, I was probably pointing the left controller down, as my arm got tited and that's why the forward direction was changing.

**Comment by DrBeef** [comment]
Can we close this?, HMD oriented directional movement will also be coming with the next update

**Comment by hfbassani** [comment]
Sure. Thanks for the replies!
