### ISSUE TITLE
Unable to select menu options after dying

### ISSUE THREAD

**Issue by manicmachine** [DrBeef/Lambda1VR#16]
While playing yesterday I had died and discovered that I was unable to resume the game due to the cursor stopping midway the screen when attempting to resume/load (approaching from the right). I was able to move the cursor to the right without issue but would stop halfway when trying to reach the menu options on the left. This behavior continued when I tried minimizing (?) the game and then resuming in addition to putting the Quest to sleep/awaken. It almost seemed like the left side was a dead zone at this point and couldn't resolve until I killed the app entirely. 

I'd be happy to provide more information if I encounter the issue again, just let me know what you'd need.

**Comment by baggyg** [comment]
Duplicate of https://github.com/DrBeef/Lambda1VR/issues/3
