### ISSUE TITLE
Laseraim bug

### ISSUE THREAD

**Issue by berndolauerto** [DrBeef/Lambda1VR#18]
When you turn on the laser sight and switch guns at last position of your laser remains static in the world and new one appears on the newly selected gun.  See picture.

![com oculus vrshell-20190801-164038 mp4_snapshot_00 11_ 2019 08 01_16 48 45](https://user-images.githubusercontent.com/24796274/62303398-55351f80-b47c-11e9-82b4-e77d2cbf64a4.jpg)
Edit: Seems like it doesn't always occur. Switching between Colt and Pistol does it more often.

**Comment by baggyg** [comment]
Do both disappear when you toggle it off?

**Comment by berndolauerto** [comment]
Sorta, they disappear when you toggle it off and chance weapon.

**Comment by DrBeef** [comment]
My laser aim changes were a little bit of a fiddle.. there's a separate laser beam for each weapon.. I need to make them all share one beam so when you change weapon the beam isn't left hanging around.

**Comment by neitey** [comment]
Wanna add that it's impossible to use laser aim and the flashlight together at the same time. (minor bug, just noticed)

**Comment by DrBeef** [comment]
Seemed to work for me when i tried it. You sure your flashlight wasn't
flat? :-D

**Comment by DrBeef** [comment]
This should be fixed in the upcoming update
