### ISSUE TITLE
Height Calibration (seated play)

### ISSUE THREAD

**Issue by cercata** [DrBeef/Lambda1VR#19]
It would nice to have a way to tweak the player height, so we can play seated, for planes, trains, buses.

In fact, this would be an option in the Oculus Setup, but that can take very long until they add it.

**Comment by DrBeef** [comment]
Should be possible.. in fact, as long as we know where the floor is, then it _should_ be possible to just adjust the height based on that.

**Comment by DrBeef** [comment]
In the next release, the in-game player height will be based on the real world user height (so if sitting down, you will be lower in the game). There will also be a cvar that allows you to adjust the height up or down in additional to the real-world height.
