### ISSUE TITLE
vr_snapturn_angle cvar isn't working

### ISSUE THREAD

**Issue by DrBeef** [DrBeef/Lambda1VR#2]
For some reason the cvar vr_snapturn_angle is always snapping to 45 degrees. Smooth turn should kick in if the value is configured to < 10 degrees, but it is ignoring the value set in the config.cfg file.

**Comment by cercata** [comment]
It seems like some cvars are being overritten with their defaults values, happens also on "vr_weaponrecoil"

**Comment by cercata** [comment]
Works perfect in version 1.0.3

**Comment by baggyg** [comment]
Thanks for confirmation. I suspect at some point it would be good to have this as a menu option, but I think this issue can now be closed.
