### ISSUE TITLE
Pistol does not shoot

### ISSUE THREAD

**Issue by Jervi71** [DrBeef/Lambda1VR#23]
Hi,
sometimes it happens that the pistol does not shoot anymore despite having ammunition. I have to exit app and reload it.

**Comment by baggyg** [comment]
We probably need a bit more information on this one. Do you notice anything else when it occurs. For example, could it be that you are firing when you pass through a load screen and it doesn't work afterwards?

**Comment by Jervi71** [comment]
Hi,
it happens while I'm playing normally. I can shoot a few shots (no through a load screen), then nothing. Sometimes it starts shooting again, other times it doesn't and I have to restart the app.

**Comment by alexmaret** [comment]
I experienced this as well. My pistol would not fire anymore, but my shotgun was in constant firing and reloading mode. The shotgun was always reloading one shell and then immediately firing it. I could neither stop the reloading/firing of the shotgun, nor could I get my pistol to fire again. 

Saving and reloading the game fixed the issue.

**Comment by neitey** [comment]
This issue is identical with issue #32.

**Comment by DrBeef** [comment]
Closing as a pull request has been submitted that should resolve this
