### ISSUE TITLE
Local multiplayer game - when the other player fires a weapon, VR player gets fire animation too

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#24]
I tried a local multiplayer game, with the server being xash3d on my firetv. Great response, no lag, amazing how much counter strike is already in HL1. 

Strange bug is, when the other player holds and fires the same gun, the VR player gets the fire animation and decals too without loosing ammunition.

minor bug, since how many people play MP. But would be nice if we actualy could play HL in MP. I forgot how good it was.

Edit: Seems only to happen with the M4/Rifle, tested it multiple times on different games.

**Comment by DrBeef** [comment]
I think it is actually the tracer, rather than actual fire.. no idea why it is happening though.

**Comment by baggyg** [comment]
I've seen this happening and couldn't work out what was going on. That it is the other player shooting makes sense. The server will be sending out messaging that the player is firing and I expect this is being misintepreted on the client side. Do you know if this occurs in the standard Xash @neitey ?

**Comment by neitey** [comment]
I occurs with all versions i tried, yes. They are the same bugs which happen when playing on an online server.

This issue can be closed, all is already documented in the other Multiplayer bug report.
