### ISSUE TITLE
[performance improvement] the fleshy blood bits are causing framedrops

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#26]
It seems that the fleshy blood bits (not sprites) that fly around and lie on the floor for a brief moment are causing big framedrops. The framedrops can be experienced everytime an enemy gets shot. framerate reduction is about 10 frames and only last for a second. 

will try around with violence.cfg. But that doesn't seem to work for the flesh bits.
We should find out which cvars switches of the fleshy bits ( i call them like that) , they are not worth the framedrops.

**Comment by TheInimitable** [comment]
They're called "gibs." And here are the cvars:

violence_ablood | Toggles alien's blood.
violence_agibs | Toggles alien's gibs.
violence_hblood | Toggles human's blood.
violence_hgibs | Toggles human's gibs.

**Comment by neitey** [comment]
Aren't that the same values as in violence.cfg. I have to try around more but i think changing these will disable gibs and blood decals also but not only the blood splash. But i have tontry more
