### ISSUE TITLE
Weapons have too much recoil animation

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#27]
I realized this when comparing them to other weapons assets i experimented with. The weapons used now have a lot of recoil / recoil animation. It's making it hard to aim with the sight. Less recoil make the weapons feel more spot on. That original recoil was good for flatscreen but not for VR.

Is this a Cvar or is it part of the animation?  Another reason to find better mid-poly weapons. (i have this on my list)

**Comment by cercata** [comment]
The first it looked to me that pistol had to much recoil, but after some time with it, i got used to it, and I like it now.
Withe other weapons I didn't expend enougth time to have an opinion

**Comment by neitey** [comment]
Since the player is encouraged to aim with the sight, the overly applied recoil breaks it a bit. Proper aiming is a hassle and could feel better. The M4 wobbles all the way, no way to use the sight is you shoot more than one bullet. The only weapon the big time recoil animation is fine is the revolver imo.

**Comment by baggyg** [comment]
This isn't a CVAR, its the animation itself. Make me a list of the weapons that you think are the worst and I can either speed up the animations or in some cases minimise them

**Comment by neitey** [comment]
I think it is just the the Beretta and the M16 which matter, because that's when the iron sight is used. All other weapons are more or less fired from the hip or with help of the laser pointer.

I have to say that i somehow got used to it and it is not that bad as my first post made it sound. I apologize for that alarming tone.

**Comment by baggyg** [comment]
Just retried it. The pistol M1911 has very minimal recoil. Is that what you mean by Beretta? I would be loath to touch it as it feels realistic to me. 

Similarly the AR16 animation is minimal. Unless there was a consensus that this was too much I don't think this needs changing. 

The only one with a big recoil was the 357 which I thought was natural but could be sped up or minimized a bit. 

Overall its a difficult trade-off. A gun in real life does recoil. we can't emulate that in VR without much much stronger haptics, therefore it has to be implied by the animation. 

When I have some time I will try some things out in Onward which I find to be realistic and see how they compare

**Comment by neitey** [comment]
I think you are right. The more i play the more appropriate the recoil seems to me. And you are also right, it not a Beretta M9 its a M1911. Let's close this.
