### ISSUE TITLE
Rifle doesn't aim strait. Model not aligned with trajectory.

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#28]
the rifle sights are not aligned with the real trajectory. The laser sight shows the real point of bullet impact, it is more to the right. weapons muzzle flash is also more to the right, not at the barrel of the gun.

So i guess the gun has to be moved a some pixel to the right. :)

**Comment by baggyg** [comment]
I suspect the origin in the gun compile is off. Work on models is ongoing so this will be fixed.

**Comment by DrBeef** [comment]
I'm going to close this as the updated models should resolve this issue.
