### ISSUE TITLE
Aiming at things above the player.

### ISSUE THREAD

**Issue by turdlar** [DrBeef/Lambda1VR#29]
Hi,

I've had a handful of annoying unavoidable deaths caused by barnacles, because i couldn't aim up to shoot them.

Trying to aim above the player (to a certain degree) makes the held weapon forcibly change its angle.

This should be very easy to replicate - let me know if i can provide additional information.

**Comment by neitey** [comment]
Also experienced it. Most of the time it's not relevant but in some situation it makes the game much harder.

**Comment by neitey** [comment]
definitely fixed

**Comment by DrBeef** [comment]
This is definitely fixed in the next update
