### ISSUE TITLE
Warping/fisheye effect

### ISSUE THREAD

**Issue by samolesen** [DrBeef/Lambda1VR#30]
When looking around in the game, the screen warps. 

The warping is obvious when first trying the game, but your brain gets more used to it over time.

Since the warping can be harder to notice after a while it is surely harder to debug, but I found a really easy way of replicating the issue:

1. Make the guardian appear, by holding a controller near the border.
2. Look around.

It should be clear that the game and guardian movement is way different. Doing the same in other games (or the oculus home screen) and you will see that the guarding looks fixed to the environment.

**Comment by samolesen** [comment]
It might be a FOV issue, but I am not sure.

**Comment by baggyg** [comment]
There is a fix for this in an upcoming version.

**Comment by samolesen** [comment]
I built the latest version a234123 and can confirm that the "virtual neck" is a major improvement.
These is still a little misaligned movement when turning the head, but now it is really only noticeable, when comparing it to the guardian.

**Comment by neitey** [comment]
I would say fixed

**Comment by samolesen** [comment]
The remaining misalignment might be caused by #38.

**Comment by DrBeef** [comment]
I increased the positional multiplier a little in the latest commit. If you are able to build and try again I would be interested to hear if that improved it. If it still isn't enough, then you could try tinkering with values of the following cvar yourself, it is currently set to 2800:

`vr_positional_factor`

**Comment by Electrikmedic** [comment]
I found that even in v1.1.0, the default FOV was still incorrect and still giving me the warping/fisheye effect (I believe it's set to around 107 by default).

When I set the FOV to 104.5, the warping is completely gone.  I did this by editing the config.cfg file with the following:

r_adjust_fov "1"
vr_fov "104.5"

In case that doesn't work, the config.cfg file that I use with the Half Life VR Gold HD texture pack is attached (rename it from config.txt to config.cfg if you want to use it)

[config.txt](https://github.com/DrBeef/Lambda1VR/files/3694043/config.txt)

**Comment by neitey** [comment]
> When I set the FOV to 104.5, the warping is completely gone. I did this by editing the config.cfg file with the following:
> 
> r_adjust_fov "1"
> vr_fov "104.5"

I will definitely check this out. And give feedback.

**Comment by neitey** [comment]
CONFIRMED. Setting it to 104 will make it behave like an native game. This needs to go i an update.

**Comment by DrBeef** [comment]
Closing as 104 is now default FOV and it does feel perfect.

**Comment by samolesen** [comment]
I agree that the ideal FOV is somewhere between 104 and 105 (though closest to 104). However, after some testing I have concluded, that there is no difference between even 104.0 and 104.9, so due to the lack of precision in the config, an FOV of 104 is indeed the best compromise.

**Comment by Kentypoo** [comment]
i tried adding these to the config files on my quest 2 today on all 3 half life games  and nothing changed.. still warps when turning head

**Comment by DrBeef** [comment]
@Kentypoo have you updated to the very latest version (released last night) and made sure to delete the config.cfg files. The warping should be fixed. The FOV is taken from the Oculus API, not from a cvar now.
