### ISSUE TITLE
Sometime weapon can't shoot. And outburst riflegrenade after load.

### ISSUE THREAD

**Issue by mixivalo** [DrBeef/Lambda1VR#32]
It happen be sometime after load. or sudden.
When I can't shoot any weapons(Except crowbar).
shotgun and riflegrenade are outburst automatically.
Please fix that bug.
(I used English Translate.

**Comment by Jervi71** [comment]
Sometimes it happens me too.

**Comment by neitey** [comment]
Can confirm. When pressing the secondary fire button and fire button, then releasing the secondary button but still pressing the fire button, can behave as the weapon has jammed. By pressing both buttons randomly this then goes away.

**Comment by dombomdom** [comment]
i made a pull request with a fix for that

**Comment by DrBeef** [comment]
I've merged the pull request.. soon as I get some time I'll put a release out with all of @dombomdom 's fixes in
