### ISSUE TITLE
Real live crouching 

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#33]
Would be nice to enable the player to crouch in real life to trigger crouch in game, as this is done by skyrim and other games.

If even possible, a real 6dof crouching mechanic would be even better. 

Expecialy game elements where the player needs to duck to evade trip mines would massively benefit from such crouch mechanics.

**Comment by berndolauerto** [comment]
Like If headset is 3/4 of standing height then trigger crouch button? Doom had that option. Worked great.

**Comment by DrBeef** [comment]
This will be in the next release..
