### ISSUE TITLE
No way to put in Console commands

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#34]
A way to put in console commands would be awesome. Especially because many modifications like Counter Strike need the player to press a button, like to choose a team.

A Keyboard substitute like we have in Quake-Quest would be great.

**Comment by DrBeef** [comment]
Whilst not a keyboard substitute, it is now posible to configure a list of console commands in the commands.lst file found in the xash folder, these can then be executed from the Commands menu in the game.
