### ISSUE TITLE
Add gamepad controller option

### ISSUE THREAD

**Issue by peanutismint** [DrBeef/Lambda1VR#36]
Unless I'm missing something it doesn't seem possible to control the game via bluetooth gamepad like I can with Quake GVR or Doom. Would this be possible to add?

**Comment by neitey** [comment]
Why would you want to substitute the oculus controllers? What benefit does
a bt gamepad give?

peanutismint <notifications@github.com> schrieb am Fr., 16. Aug. 2019,
07:50:

**Comment by DrBeef** [comment]
I'm afraid I won't be adding gamepad support myself. Anyone is welcome to fork the repo and add the necessary support (and I'll point them to the right location) and submit a pull request.

Closing this issue for now.

**Comment by peanutismint** [comment]
Well because in my case (oculus go) I only have the one 3DOF controller
and it doesn’t have a thumb stick so control is pretty much impossible.
Also only one button of my controller actually seems to do anything, which
is the trigger which initiates Crouch I believe?! So can pad or
keyboard/mouse control is pretty much a requirement for me.
