### ISSUE TITLE
The grenade throwing is a bit too sensitive 

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#37]
The new grenade throwing mechanic is rat and fun. To make it even better i would suggest to make the throwing less sensitive. Now the grenade feels and behaves like it has the weight of a tennis-ball or less. I think the player has to be too careful, in the heat of the battle, i often throw a home run to the end of the room, missing my target by 10 meters. I think many players are "corrupted" :) by superhot where you have to use much force when throwing stuff.

I think making the grenades act a little less sensitive would add to the gameplay.

**Comment by DrBeef** [comment]
Will be fixed in next update
