### ISSUE TITLE
Arena scale / Room scale. 1 meter ingame isn't matching 1 meter in real world

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#38]
It's slightly off. It is visible when the guardian is showing. When walking room scale, it has the effect of walking against a very slow treadmill. Not a big thing, but it makes it Arenascale a bit less fun.

**Comment by DrBeef** [comment]
Suspect my positional coefficient is slightly off.. will tweak the value and see what happens.

**Comment by DrBeef** [comment]
I increased the positional multiplier a little in the latest commit. You could try tinkering with values of the following cvar yourself, it is now currently set to 2800, if that isn't quite enough, then increasing a little bit more might be necessary:

`vr_positional_factor`

**Comment by samolesen** [comment]
I tried it and noticed something weird (both in current and previous commit): The walking speed (when walking in roomscale) seems to depend on the headset orientation. I.e. when looking towards "north" or "south" in-game, walking in _any_ direction is basically 1:1 (maybe needs minor tweaks, but hard to see now). However, when looking towards "east" or "west", the in-game walking speed is around 50-100% faster in any direction.

**Comment by neitey** [comment]
fixed with latest release

**Comment by neitey** [comment]
vr_positional_factor 2900
