### ISSUE TITLE
Getting error when trying to copy files in Sidequest

### ISSUE THREAD

**Issue by Drtrollmiester** [DrBeef/Lambda1VR#39]
I get this error whenever I attempt to drag the necessary file into Sidequest 
![image](https://user-images.githubusercontent.com/54778550/64081150-f1945100-ccca-11e9-9975-a7df380a0c3e.png)

**Comment by neitey** [comment]
I would think this has most likely nothing to do with lambda1VR and more
with Sidequest.

Drtrollmiester <notifications@github.com> schrieb am So., 1. Sep. 2019,
21:12:

**Comment by Drtrollmiester** [comment]
I really put this here to see if more people had the issue or had run into it. I would love to hit up the Sidequest team but if anyone here was seeing this or had seen it. Guidance would be much appreciated.

**Comment by DrBeef** [comment]
Did you manage to get this working?, I would like to close this as it is unrelated to this project really. If you are having issues I'd recommend joining the sidequest discord, everyone is very helpful on there.
