### ISSUE TITLE
Headcrabs can't be shot (aiming is to high, not only on headcrabs)

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#4]
Even on very short range headcrabs suffer no damage from pistol. Crowbar kills them though.
Doesn't seem to be an issue with the aiming.

Will evaluate and test some more.

**Comment by baggyg** [comment]
Quite a few people are reporting similar issues. However I don't think there is actually an issue here other than:
The pistol aiming slightly upward by default.
No hit animations in HL. 

Make sure you are aiming down the sights as you would a regular gun and try again. I will endeavour to test today and show a video of it working.

**Comment by baggyg** [comment]
Having tried to disprove you, I actually encountered the same. I could kill everything else (eventually) with a pistol but not individual head crabs. Will investigate further

**Comment by neitey** [comment]
As you said aiming is spot on. strange behaviour, will later try with other weapons.

**Comment by baggyg** [comment]
Ok, so the problem with the pistol seems to be the ray tracing. If I fire above a head crab I tend to hit it.  In fact even the bullethole decal doesn't seem to match up with the ray tracing.

**Comment by neitey** [comment]
> Ok, so the problem with the pistol seems to be the ray tracing. If I fire above a head crab I tend to hit it. In fact even the bullethole decal doesn't seem to match up with the ray tracing.

Just came here to say the same. strange. yeah decals and actual hit aren't the same.

**Comment by baggyg** [comment]
Fixed on latest release (1.0.3)
