### ISSUE TITLE
(New Update) Laser sight of the Assault Rifle does not match the iron sight

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#41]
There is a big difference between the two point, causing the player to miss a lot of headshots when aiming only with iron sights.

Sidenote, also if there is any way to make the iron sight "hole" a big bigger that would be great. It is really hard to aim through that tiny thing.

**Comment by baggyg** [comment]
Could you describe the difference between the two?  In other words how would the laser sight need to be moved? 

I saw your latest video and the laser seems to be pointing directly forward from the gun. All I have is two controls, the origin of the gun (which is also the rotation point) and the direction on the forward plane. There is no option for tilting up or down. 

Unless you think it is to the left or right I think what you are looking for would be the origin to be exactly at the back sight. However this would look very weird as the laser would originate above the gun as well as making the weapon rotation weird.  

Let me know your thoughts as I don't think there is a better compromise here

**Comment by neitey** [comment]
When i aim with the iron sight properly,the hits are all too high and the laser also aims a few degrees higher. The laser sight shows the real trajectory and is correct.
I am not sure how you can fix this. Since the lasers origin is properly aligned  

This is not a deal breaker but this way the iron sight is not super accurate. And the player has to compensate. Maybe it's just me my 10 months military times are long over and i never shot an actual Colt AR15 /M16.

Maybe we can have a second opinion on this from someone?

**Comment by baggyg** [comment]
Ok, thats something to work with. I would have expected them to be lower. If there is higher I may be able to adjust the height of the front scope to line it up

**Comment by neitey** [comment]
Don't take my work, it is easy to see when you align the sight properly that the laser/point of impact is a bit off, this inaccuracy gets worse the more far the player is from its target.

**Comment by baggyg** [comment]
OK, I had a close look at this. It is difficult to tell as the hole is so small (I can look to enlarge that). Over a few metres it doesn't make any difference but as you say over 10+ metres it is noticeable. I'll try to adjust the sights to get to a happy medium. 

Similarly the pistol isn't aligned perfectly - I can fix that. 

Will prepare both for next release

**Comment by baggyg** [comment]
These are both fixed and will be in 1.1.2

**Comment by neitey** [comment]
very much fixed!
