### ISSUE TITLE
Repeatable crash during Apprehension

### ISSUE THREAD

**Issue by loganlemmon** [DrBeef/Lambda1VR#44]
When the player finishes the first ninja fight in Apprehension, they must exit via the Surface door where Gordon gets knocked out and the screen goes black. Right after the audio plays of "we got him..." the app crashes out to the home screen.

**Comment by DrBeef** [comment]
I'm almost at that point myself.. I'll investigate when I get there

**Comment by loganlemmon** [comment]
Laser sight was off. I tested again on the newest version and it didn’t crash, although the locked perspective on the cutscene was pretty rough sim-sickness-wise! Thanks for looking into it.
