### ISSUE TITLE
In v1.1.2 laser beams don't disapear

### ISSUE THREAD

**Issue by TiliSleepStealer** [DrBeef/Lambda1VR#47]
In v1.1.2 around a load of a new level, I see laser beams kinda floating in the air, not attached to any weapon of mine. These laser beams are coming from locations I could not reach.

**Comment by neitey** [comment]
As a quick fix disable the laser before saving.

TiliSleepStealer <notifications@github.com> schrieb am Sa., 12. Okt. 2019,
14:02:

**Comment by DrBeef** [comment]
These laser-sight beams have become the bain of my life!

I think they have always had a bit of an issue of not disappearing occasionally to be honest, I will consider ways to fix it, but it doesn't feel like a high priority at the moment.

**Comment by TiliSleepStealer** [comment]
Yeah I agree, totally not high prio. It's just good to have the bug logged.

**Comment by dombomdom** [comment]
Hi, i have a simple fix for the multi laser bug after saving on https://github.com/DrBeef/hlsdk-xash3d

**Comment by DrBeef** [comment]
Closing this as @dombomdom 's fix has been merged to master and will be in the next update
