### ISSUE TITLE
People get the old big hand grenade model if they copy the valve_hd folder over 

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#48]
It seems the new and better hardcoded grenade model gets overwritten when the models from valve_hd are used.

**Comment by baggyg** [comment]
It shouldn't unless they have the no_copy file there. I can't think of a reason why as it copies on every game load. 

Only other option would be if the HD file had a different naming convention that the engine recognised

**Comment by neitey** [comment]
i will check, i made a clean reinstall maybe it was my installation before. will close this.
