### ISSUE TITLE
Pistol does not have reload sound.

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#52]
Did a fresh install to rule out errors and as some users noted, the pistole does not have any reload sound. So does the revolver. HD pack was not installed at all. Totally vanilla Valve folder. 

Is it my install or is it really missing?

**Comment by neitey** [comment]
I did a new vanilla installation, unmodded and the reload sound of the pistol and the revolver are definitely missing. No idea what might cause this.

**Comment by baggyg** [comment]
Could be the altered pistol. I need to check the compile file and initial file copies

**Comment by baggyg** [comment]
Fixed and ready for next release >1.2.5
