### ISSUE TITLE
Gun orientation is fixed and pointing backwards

### ISSUE THREAD

**Issue by mnmean** [DrBeef/Lambda1VR#55]
Edit: Never mind! THis is caused by me hitting the grip button with my left hand. I do this all the time! Maybe make all grip buttons drop a grenade when pressed and I'll learn! 

So I've had this problem crop up briefly, usually in tight corners, but now it seems to be permanent. All weapons are pointing down and to the left. I can move them around, but I can't change their orientation, which makes it almost impossible to hit anything. 

I've been using HL-Gold textures, but everything else is standard.

**Comment by DrBeef** [comment]
> Maybe make all grip buttons drop a grenade when pressed and I'll learn!

hahaha.. glad you got to the bottom of it. I'll close this
