### ISSUE TITLE
Revolver does aim to low - not same with laser

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#56]
Sorry, baggyg in the last revision of the wepaons i did not notice this. The revolver aims too low, when using the iron sight. Real point of impact( marked by the laser) is not hit when using proper iron sight aiming.

**Comment by baggyg** [comment]
I had a go at this and to be honest think it is about as accurate as it can be, without getting ultra accurate (which seems pointless considering the bullet spread). Looking down the sights pretty much matches up with the laser for me... certainly no where near as obvious an error as the rifle.

**Comment by neitey** [comment]
I really love what you did with the weapons.  I don't think i would have played HL till the end without those brilliant iron sight weapons. Aiming for real adds so much to the game.
So i really hate to have an different opinion on this one.

The Revolver almost has no bullet spread, so every inaccuracy is noticeable. (Beside the crossbow, the revolver is kind of the sniper weapon in HL) 
HL has a "Headshot hitbox" so now when you aim the revolver to the head using iron sights, you end up hitting the chest.

I went back into the game to check if i am imagining things but no. The bullet point of impact matches up with the laser but not with the iron sight. 

You can clearly see it in the video: https://youtu.be/FLs5inRpnPQ

> certainly no where near as obvious an error as the rifle.
I am not sure if i understand you correctly. But the Ar-15 seems to be aligned perfectly. Maybe i misunderstood.

BUT since nobody else noticed it or complains here or on r/lambda1vr i guess this issue can be closed. Especially if it is a lot of hassle to fix.

**Comment by baggyg** [comment]
Thanks for the video - that would certainly explain our differing opinions since we are looking at two different guns! I assumed you meant the standard gun. I'll have another look at the 357

**Comment by neitey** [comment]
Ah ok. No the Pistol is very fine! Yes i mean the piff paff cowboy gun :)

**Comment by baggyg** [comment]
This is fixed ready for next minor release
