### ISSUE TITLE
Ladders are hard to climb cause controls are HMD and off-hand oriented at the same time.

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#57]

**Comment by neitey** [comment]
That is basically why many people think it is a bit of a coin throwing when climbing ladders. They have the feeling they do everything right and still they sometimes fall without any particular reason.

I would be a bit gain to get rid of one of the orientations. Most preferably the hmd orientation, cause people tend to look left an right while climbing.

**Comment by DrBeef** [comment]
Should now be fixed in the latest update v1.2.3

**Comment by jdawgzim** [comment]
What am I doing wrong?  I can only go up in swimming and ladders 1/4 of the time.  I face up, push forward, and point my controller up...    Then it goes down or sideways.   I can't figure this out.  I have the latest install from SideQuest.  Am I doing something wrong or is this still bugged?

**Comment by neitey** [comment]
> What am I doing wrong? I can only go up in swimming and ladders 1/4 of the time. I face up, push forward, and point my controller up... Then it goes down or sideways. I can't figure this out. I have the latest install from SideQuest. Am I doing something wrong or is this still bugged?

Make sure you are really on the latest version. To climb ladders only point the off controller upwards and push the thumbstick forward. to swim up and down, just press A and B (if you use the default sheme)

**Comment by jdawgzim** [comment]
I'll try again tonight.  I think I might have been pointing my left controller a little too high making the game think I was facing away from the ladder.
