### ISSUE TITLE
Port of the Xash3D-FWG Half Life Engine to Oculus Quest

### ISSUE THREAD

**Issue by sergiopoverony** [DrBeef/Lambda1VR#58]
You lose  **S** In FWGS name

**Comment by tunbridgep** [comment]
Once it's on the quest, does this mean it can potentially become easier to port to any openVR compatible system?

I think it's only fitting in an ironic way that Half-Life be playable in VR on a Valve Index

**Comment by DrBeef** [comment]
Fixed the original issue in the description, thank-you for pointing it out!

@tunbridgep this is an android based engine port, so won't run on the Index.. there is a PCVR HL mod being created as we speak and it nearing its first public beta I understand.
