### ISSUE TITLE
Will this also be compatible with HTC Vive?

### ISSUE THREAD

**Issue by danylopez123** [DrBeef/Lambda1VR#59]
I saw this VR Mod for Half-Life, but i don't have an Oculus Quest.
I only have the HTC Vive.

Will this also be compatible for HTC Vive in the future?

**Comment by tunbridgep** [comment]
I am not a developer on this project, so I can't say with any degree of authority, but I have heard that OpenVR support is a goal for the future. At that point, your HTC Vive will be supported, along with a lot of other HMDs

**Comment by neitey** [comment]
> At that point, your HTC Vive will be supported

No, Lambda1VR will never run on a windows based machine. It is solely an port for android based standalone hmds like the Quest. 

You start to mix things up - this is lambda1VR the HL port for Oculus Quest  by DR BEEF.
There is a HL port for openvr in the making by max vollmer, but that is a completely different project.

**Comment by DrBeef** [comment]
Thanks @neitey , closing this now.
