### ISSUE TITLE
Weapon Angles are terrible

### ISSUE THREAD

**Issue by DrBeef** [DrBeef/Lambda1VR#6]
- Guns need to be dropped by about 20 degrees
- Crowbar needs to be lifted by about 30 degrees

**Comment by Jervi71** [comment]
Confirm. Above all it is difficult to hit with a gun.

**Comment by milesrotaru** [comment]
In addition to angle adjustment the position of Gordon's hand should match the player's hand.

**Comment by neitey** [comment]
> In addition to angle adjustment the position of Gordon's hand should match the player's hand. 

Yeah the hand / weapons position is still a bit off but ok.

It seems the crowbar still need 10 degreed lifting, weapons need 10 more degree dropping to match the angel of the controllers handle perfectly.

**Comment by DrBeef** [comment]
You could try some values yourself by adjusting the vr_weapon_pitchadjust cvar,
it is set to -20, you could try -30 and between.

I tried lifting the crowbar, but it starts making the 6DoF go funny.. so I
left it as it was.

**Comment by DrBeef** [comment]
Weapon angles are fixed and correct in the next release
