### ISSUE TITLE
Cannot use health station or pick up health packs

### ISSUE THREAD

**Issue by thoros1179** [DrBeef/Lambda1VR#63]
See [this video](https://youtu.be/0rdRJBnF6uw)
Version is latest as of today.
But the savegame is older from August.

**Comment by baggyg** [comment]
That video shows you already have 100% health, so what effect would you expect to happen?
Additionally the sound shows the action is being undertaken. 

I cannot see any bug as things stand.

**Comment by thoros1179** [comment]
I'm so dumb. I mistook the shield display for health... apologies.
