### ISSUE TITLE
Swim Down is broken.

### ISSUE THREAD

**Issue by Maxxgold** [DrBeef/Lambda1VR#66]
When you press the jump button you go towards the surface.

When you press the crouch button nothing happens.

If you aim the flashlight down, you don't go directly down. It's janky at best. I'm at the part when you have to dive down from a tower and turn a valve in the water. I can get to the valve but it takes so long that I end up dying. All of this could be eliminated if crouch was used to dive.

Quake2Quest has perfect swimming. Jump takes you up and crouch takes you down. Can you please implement that here/

**Comment by DrBeef** [comment]
This should now work as requested in the latest release
