### ISSUE TITLE
[Advice] After copying files to the Quest/xash3d folder, a restart of the device is mandatory! 

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#7]
Doesn't matter if it a texture files or just savegames. Without a restart of the quest the files often won't get recognized.  I think this has more to do with the android file system than lambda1Vr. So not really a bug, but maybe a thing to stress out in a upcoming guide or somthing like it.

**Comment by cercata** [comment]
It's on the readme:

> - After changing files in xash/vale folder, often the device needs to be restarted for the game to use the changed files.

**Comment by neitey** [comment]
Did not see it, thx
