### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by michielproce** [DrBeef/Lambda1VR#76]
Following the instructions under **Building** in the README.md, I cannot get the project to build.

I keep running into the problem: `Execution failed for task ':VrSamples:Lambda1VR:Projects:Android:generateJsonModelRelease'.` I've tried a lot to fix it but I've been unable to tackle the problem. The suggested docker also fails to build.

I'm running Android Developer Studio 3.6.1 and NDK 21 on Windows 10 64bit. 
Attached is the output of my build: [build-output.txt](https://github.com/DrBeef/Lambda1VR/files/4345946/build-output.txt)

**Comment by michielproce** [comment]
I needed to clone submodules as well:
```git clone --recurse-submodules https://github.com/DrBeef/Lambda1VR.git```

Also I needed to move the Oculus Mobile SDK near the root of my drive (I used ```C:\ovr```) to not exceed the Windows character path limit

**Comment by michielproce** [comment]
Also had to change ```-std=c99``` to ```-std=gnu99``` in ```gl4es\Android.mk``` to mitigate an ‘asm’ undeclared error.
Is this the correct way to fix this? The build succeeds this way.

**Comment by yingtian991221** [comment]
> Also had to change `-std=c99` to `-std=gnu99` in `gl4es\Android.mk` to mitigate an ‘asm’ undeclared error. Is this the correct way to fix this? The build succeeds this way.

Your solutions are so helpful that these two steps solves my building issues. I didn't even thought the problem could be caused by too long path.
