### ISSUE TITLE
Corrupt textures (grey lines) 

### ISSUE THREAD

**Issue by QUAKEULUS** [DrBeef/Lambda1VR#77]
Not sure what is causing this, it goes away after reloading.

![image](https://user-images.githubusercontent.com/9068677/79438639-a3e20580-7f88-11ea-83be-6b0b445cc728.png)

**Comment by baggyg** [comment]
Turn of VBO in the video options

**Comment by QUAKEULUS** [comment]
Thanks! What other glitches may VBO show up as?
