### ISSUE TITLE
Gameplay can't be recorded

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#8]
Not a real issue, but will hurt your fame and glory on youtube :).

And to be honest, it is nice to show HL1 VR to others. Was possible with the pre-release, though.

**Comment by baggyg** [comment]
Odd, since I literally just recorded and downloaded a video using the release build:

https://youtu.be/bTMK-YTyovg

**Comment by DrBeef** [comment]
Yeah, works for me too

**Comment by neitey** [comment]
Strange, it always says "this content can't be shared"

will reinstall from scratch

**Comment by baggyg** [comment]
Let us know if you still get this. If not I think this one can be closed as not seen it reported anywhere else.

**Comment by neitey** [comment]
It's an issue on my side ... going for a factory reset.
