### ISSUE TITLE
Default gamma value seems to be a bit to high, making the game look more ugly than it has to be. (more opinion than issue)

### ISSUE THREAD

**Issue by neitey** [DrBeef/Lambda1VR#9]

**Comment by neitey** [comment]
i will close this in one day

**Comment by DrBeef** [comment]
Probably an easy fix, leave this open and I'll tweak it..

**Comment by baggyg** [comment]
There is a gamma setting in the config. Not sure if this affects it. Also is this not an option from the Video screen in Configuration?

I agree if we are just talking about default this could be a tad lower.

**Comment by neitey** [comment]
Just for the casual Joe who enters the game, even won't enter the options. Lighting looks terrible with default settings.

**Comment by neitey** [comment]
Seems to be fixed, looks better now out of the box.
