### ISSUE TITLE
[request] Pico 4 Version?

### ISSUE THREAD

**Issue by BobbyMcJefferson** [DrBeef/Lambda1VR#93]
Would it be possible to port this to the Pico 4? From what I've seen, the internals are very similar to the Quest 2. The Pico 4 has more RAM though. Somebody already ported the Quest 2 version of Quake III Arena to the Pico 4: https://github.com/lvonasek/quake3pico
So maybe this one should be easy to port?

**Comment by baggyg** [comment]
https://twitter.com/grantjbagwell/status/1585264719061024768
